/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDoctorantRouteImport } from './routes/dashboard.doctorant'
import { Route as DashboardDirecteurRouteImport } from './routes/dashboard.directeur'
import { Route as DashboardChercheurRouteImport } from './routes/dashboard.chercheur'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardDirecteurIndexRouteImport } from './routes/dashboard.directeur.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardAdminPublicationsRouteImport } from './routes/dashboard.admin.publications'
import { Route as DashboardAdminEquipesRouteImport } from './routes/dashboard.admin.equipes'
import { Route as DashboardAdminDoctorantsRouteImport } from './routes/dashboard.admin.doctorants'
import { Route as DashboardAdminBilansRouteImport } from './routes/dashboard.admin.bilans'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDoctorantRoute = DashboardDoctorantRouteImport.update({
  id: '/dashboard/doctorant',
  path: '/dashboard/doctorant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDirecteurRoute = DashboardDirecteurRouteImport.update({
  id: '/dashboard/directeur',
  path: '/dashboard/directeur',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChercheurRoute = DashboardChercheurRouteImport.update({
  id: '/dashboard/chercheur',
  path: '/dashboard/chercheur',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDirecteurIndexRoute = DashboardDirecteurIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDirecteurRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminPublicationsRoute =
  DashboardAdminPublicationsRouteImport.update({
    id: '/publications',
    path: '/publications',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminEquipesRoute = DashboardAdminEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminDoctorantsRoute =
  DashboardAdminDoctorantsRouteImport.update({
    id: '/doctorants',
    path: '/doctorants',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminBilansRoute = DashboardAdminBilansRouteImport.update({
  id: '/bilans',
  path: '/bilans',
  getParentRoute: () => DashboardAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/chercheur': typeof DashboardChercheurRoute
  '/dashboard/directeur': typeof DashboardDirecteurRouteWithChildren
  '/dashboard/doctorant': typeof DashboardDoctorantRoute
  '/dashboard/admin/bilans': typeof DashboardAdminBilansRoute
  '/dashboard/admin/doctorants': typeof DashboardAdminDoctorantsRoute
  '/dashboard/admin/equipes': typeof DashboardAdminEquipesRoute
  '/dashboard/admin/publications': typeof DashboardAdminPublicationsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/directeur/': typeof DashboardDirecteurIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/chercheur': typeof DashboardChercheurRoute
  '/dashboard/doctorant': typeof DashboardDoctorantRoute
  '/dashboard/admin/bilans': typeof DashboardAdminBilansRoute
  '/dashboard/admin/doctorants': typeof DashboardAdminDoctorantsRoute
  '/dashboard/admin/equipes': typeof DashboardAdminEquipesRoute
  '/dashboard/admin/publications': typeof DashboardAdminPublicationsRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/directeur': typeof DashboardDirecteurIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/chercheur': typeof DashboardChercheurRoute
  '/dashboard/directeur': typeof DashboardDirecteurRouteWithChildren
  '/dashboard/doctorant': typeof DashboardDoctorantRoute
  '/dashboard/admin/bilans': typeof DashboardAdminBilansRoute
  '/dashboard/admin/doctorants': typeof DashboardAdminDoctorantsRoute
  '/dashboard/admin/equipes': typeof DashboardAdminEquipesRoute
  '/dashboard/admin/publications': typeof DashboardAdminPublicationsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/directeur/': typeof DashboardDirecteurIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/chercheur'
    | '/dashboard/directeur'
    | '/dashboard/doctorant'
    | '/dashboard/admin/bilans'
    | '/dashboard/admin/doctorants'
    | '/dashboard/admin/equipes'
    | '/dashboard/admin/publications'
    | '/dashboard/admin/'
    | '/dashboard/directeur/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/chercheur'
    | '/dashboard/doctorant'
    | '/dashboard/admin/bilans'
    | '/dashboard/admin/doctorants'
    | '/dashboard/admin/equipes'
    | '/dashboard/admin/publications'
    | '/dashboard/admin'
    | '/dashboard/directeur'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/chercheur'
    | '/dashboard/directeur'
    | '/dashboard/doctorant'
    | '/dashboard/admin/bilans'
    | '/dashboard/admin/doctorants'
    | '/dashboard/admin/equipes'
    | '/dashboard/admin/publications'
    | '/dashboard/admin/'
    | '/dashboard/directeur/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardChercheurRoute: typeof DashboardChercheurRoute
  DashboardDirecteurRoute: typeof DashboardDirecteurRouteWithChildren
  DashboardDoctorantRoute: typeof DashboardDoctorantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/doctorant': {
      id: '/dashboard/doctorant'
      path: '/dashboard/doctorant'
      fullPath: '/dashboard/doctorant'
      preLoaderRoute: typeof DashboardDoctorantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/directeur': {
      id: '/dashboard/directeur'
      path: '/dashboard/directeur'
      fullPath: '/dashboard/directeur'
      preLoaderRoute: typeof DashboardDirecteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/chercheur': {
      id: '/dashboard/chercheur'
      path: '/dashboard/chercheur'
      fullPath: '/dashboard/chercheur'
      preLoaderRoute: typeof DashboardChercheurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/directeur/': {
      id: '/dashboard/directeur/'
      path: '/'
      fullPath: '/dashboard/directeur/'
      preLoaderRoute: typeof DashboardDirecteurIndexRouteImport
      parentRoute: typeof DashboardDirecteurRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/publications': {
      id: '/dashboard/admin/publications'
      path: '/publications'
      fullPath: '/dashboard/admin/publications'
      preLoaderRoute: typeof DashboardAdminPublicationsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/equipes': {
      id: '/dashboard/admin/equipes'
      path: '/equipes'
      fullPath: '/dashboard/admin/equipes'
      preLoaderRoute: typeof DashboardAdminEquipesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/doctorants': {
      id: '/dashboard/admin/doctorants'
      path: '/doctorants'
      fullPath: '/dashboard/admin/doctorants'
      preLoaderRoute: typeof DashboardAdminDoctorantsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/bilans': {
      id: '/dashboard/admin/bilans'
      path: '/bilans'
      fullPath: '/dashboard/admin/bilans'
      preLoaderRoute: typeof DashboardAdminBilansRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminBilansRoute: typeof DashboardAdminBilansRoute
  DashboardAdminDoctorantsRoute: typeof DashboardAdminDoctorantsRoute
  DashboardAdminEquipesRoute: typeof DashboardAdminEquipesRoute
  DashboardAdminPublicationsRoute: typeof DashboardAdminPublicationsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminBilansRoute: DashboardAdminBilansRoute,
  DashboardAdminDoctorantsRoute: DashboardAdminDoctorantsRoute,
  DashboardAdminEquipesRoute: DashboardAdminEquipesRoute,
  DashboardAdminPublicationsRoute: DashboardAdminPublicationsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardDirecteurRouteChildren {
  DashboardDirecteurIndexRoute: typeof DashboardDirecteurIndexRoute
}

const DashboardDirecteurRouteChildren: DashboardDirecteurRouteChildren = {
  DashboardDirecteurIndexRoute: DashboardDirecteurIndexRoute,
}

const DashboardDirecteurRouteWithChildren =
  DashboardDirecteurRoute._addFileChildren(DashboardDirecteurRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardChercheurRoute: DashboardChercheurRoute,
  DashboardDirecteurRoute: DashboardDirecteurRouteWithChildren,
  DashboardDoctorantRoute: DashboardDoctorantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
