/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDoctorantRouteImport } from './routes/dashboard.doctorant'
import { Route as DashboardDirecteurRouteImport } from './routes/dashboard.directeur'
import { Route as DashboardChercheurRouteImport } from './routes/dashboard.chercheur'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardDoctorantIndexRouteImport } from './routes/dashboard.doctorant.index'
import { Route as DashboardDirecteurIndexRouteImport } from './routes/dashboard.directeur.index'
import { Route as DashboardChercheurIndexRouteImport } from './routes/dashboard.chercheur.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardDoctorantTheseRouteImport } from './routes/dashboard.doctorant.these'
import { Route as DashboardDoctorantPublicationsRouteImport } from './routes/dashboard.doctorant.publications'
import { Route as DashboardDoctorantBilanRouteImport } from './routes/dashboard.doctorant.bilan'
import { Route as DashboardDirecteurPublicationsRouteImport } from './routes/dashboard.directeur.publications'
import { Route as DashboardDirecteurProjetsRouteImport } from './routes/dashboard.directeur.projets'
import { Route as DashboardDirecteurInscriptionsRouteImport } from './routes/dashboard.directeur.inscriptions'
import { Route as DashboardDirecteurEquipesRouteImport } from './routes/dashboard.directeur.equipes'
import { Route as DashboardDirecteurChercheursRouteImport } from './routes/dashboard.directeur.chercheurs'
import { Route as DashboardDirecteurBilansRouteImport } from './routes/dashboard.directeur.bilans'
import { Route as DashboardChercheurPublicationsRouteImport } from './routes/dashboard.chercheur.publications'
import { Route as DashboardChercheurBilanRouteImport } from './routes/dashboard.chercheur.bilan'
import { Route as DashboardAdminPublicationsRouteImport } from './routes/dashboard.admin.publications'
import { Route as DashboardAdminMessagesRouteImport } from './routes/dashboard.admin.messages'
import { Route as DashboardAdminEquipesRouteImport } from './routes/dashboard.admin.equipes'
import { Route as DashboardAdminDoctorantsRouteImport } from './routes/dashboard.admin.doctorants'
import { Route as DashboardAdminDirecteursRouteImport } from './routes/dashboard.admin.directeurs'
import { Route as DashboardDirecteurBilansIdRouteImport } from './routes/dashboard.directeur.bilans.$id'

const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDoctorantRoute = DashboardDoctorantRouteImport.update({
  id: '/dashboard/doctorant',
  path: '/dashboard/doctorant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDirecteurRoute = DashboardDirecteurRouteImport.update({
  id: '/dashboard/directeur',
  path: '/dashboard/directeur',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChercheurRoute = DashboardChercheurRouteImport.update({
  id: '/dashboard/chercheur',
  path: '/dashboard/chercheur',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDoctorantIndexRoute = DashboardDoctorantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDoctorantRoute,
} as any)
const DashboardDirecteurIndexRoute = DashboardDirecteurIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDirecteurRoute,
} as any)
const DashboardChercheurIndexRoute = DashboardChercheurIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardChercheurRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardDoctorantTheseRoute = DashboardDoctorantTheseRouteImport.update({
  id: '/these',
  path: '/these',
  getParentRoute: () => DashboardDoctorantRoute,
} as any)
const DashboardDoctorantPublicationsRoute =
  DashboardDoctorantPublicationsRouteImport.update({
    id: '/publications',
    path: '/publications',
    getParentRoute: () => DashboardDoctorantRoute,
  } as any)
const DashboardDoctorantBilanRoute = DashboardDoctorantBilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => DashboardDoctorantRoute,
} as any)
const DashboardDirecteurPublicationsRoute =
  DashboardDirecteurPublicationsRouteImport.update({
    id: '/publications',
    path: '/publications',
    getParentRoute: () => DashboardDirecteurRoute,
  } as any)
const DashboardDirecteurProjetsRoute =
  DashboardDirecteurProjetsRouteImport.update({
    id: '/projets',
    path: '/projets',
    getParentRoute: () => DashboardDirecteurRoute,
  } as any)
const DashboardDirecteurInscriptionsRoute =
  DashboardDirecteurInscriptionsRouteImport.update({
    id: '/inscriptions',
    path: '/inscriptions',
    getParentRoute: () => DashboardDirecteurRoute,
  } as any)
const DashboardDirecteurEquipesRoute =
  DashboardDirecteurEquipesRouteImport.update({
    id: '/equipes',
    path: '/equipes',
    getParentRoute: () => DashboardDirecteurRoute,
  } as any)
const DashboardDirecteurChercheursRoute =
  DashboardDirecteurChercheursRouteImport.update({
    id: '/chercheurs',
    path: '/chercheurs',
    getParentRoute: () => DashboardDirecteurRoute,
  } as any)
const DashboardDirecteurBilansRoute =
  DashboardDirecteurBilansRouteImport.update({
    id: '/bilans',
    path: '/bilans',
    getParentRoute: () => DashboardDirecteurRoute,
  } as any)
const DashboardChercheurPublicationsRoute =
  DashboardChercheurPublicationsRouteImport.update({
    id: '/publications',
    path: '/publications',
    getParentRoute: () => DashboardChercheurRoute,
  } as any)
const DashboardChercheurBilanRoute = DashboardChercheurBilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => DashboardChercheurRoute,
} as any)
const DashboardAdminPublicationsRoute =
  DashboardAdminPublicationsRouteImport.update({
    id: '/publications',
    path: '/publications',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminMessagesRoute = DashboardAdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminEquipesRoute = DashboardAdminEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminDoctorantsRoute =
  DashboardAdminDoctorantsRouteImport.update({
    id: '/doctorants',
    path: '/doctorants',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminDirecteursRoute =
  DashboardAdminDirecteursRouteImport.update({
    id: '/directeurs',
    path: '/directeurs',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardDirecteurBilansIdRoute =
  DashboardDirecteurBilansIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardDirecteurBilansRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/chercheur': typeof DashboardChercheurRouteWithChildren
  '/dashboard/directeur': typeof DashboardDirecteurRouteWithChildren
  '/dashboard/doctorant': typeof DashboardDoctorantRouteWithChildren
  '/dashboard/admin/directeurs': typeof DashboardAdminDirecteursRoute
  '/dashboard/admin/doctorants': typeof DashboardAdminDoctorantsRoute
  '/dashboard/admin/equipes': typeof DashboardAdminEquipesRoute
  '/dashboard/admin/messages': typeof DashboardAdminMessagesRoute
  '/dashboard/admin/publications': typeof DashboardAdminPublicationsRoute
  '/dashboard/chercheur/bilan': typeof DashboardChercheurBilanRoute
  '/dashboard/chercheur/publications': typeof DashboardChercheurPublicationsRoute
  '/dashboard/directeur/bilans': typeof DashboardDirecteurBilansRouteWithChildren
  '/dashboard/directeur/chercheurs': typeof DashboardDirecteurChercheursRoute
  '/dashboard/directeur/equipes': typeof DashboardDirecteurEquipesRoute
  '/dashboard/directeur/inscriptions': typeof DashboardDirecteurInscriptionsRoute
  '/dashboard/directeur/projets': typeof DashboardDirecteurProjetsRoute
  '/dashboard/directeur/publications': typeof DashboardDirecteurPublicationsRoute
  '/dashboard/doctorant/bilan': typeof DashboardDoctorantBilanRoute
  '/dashboard/doctorant/publications': typeof DashboardDoctorantPublicationsRoute
  '/dashboard/doctorant/these': typeof DashboardDoctorantTheseRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/chercheur/': typeof DashboardChercheurIndexRoute
  '/dashboard/directeur/': typeof DashboardDirecteurIndexRoute
  '/dashboard/doctorant/': typeof DashboardDoctorantIndexRoute
  '/dashboard/directeur/bilans/$id': typeof DashboardDirecteurBilansIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/dashboard/admin/directeurs': typeof DashboardAdminDirecteursRoute
  '/dashboard/admin/doctorants': typeof DashboardAdminDoctorantsRoute
  '/dashboard/admin/equipes': typeof DashboardAdminEquipesRoute
  '/dashboard/admin/messages': typeof DashboardAdminMessagesRoute
  '/dashboard/admin/publications': typeof DashboardAdminPublicationsRoute
  '/dashboard/chercheur/bilan': typeof DashboardChercheurBilanRoute
  '/dashboard/chercheur/publications': typeof DashboardChercheurPublicationsRoute
  '/dashboard/directeur/bilans': typeof DashboardDirecteurBilansRouteWithChildren
  '/dashboard/directeur/chercheurs': typeof DashboardDirecteurChercheursRoute
  '/dashboard/directeur/equipes': typeof DashboardDirecteurEquipesRoute
  '/dashboard/directeur/inscriptions': typeof DashboardDirecteurInscriptionsRoute
  '/dashboard/directeur/projets': typeof DashboardDirecteurProjetsRoute
  '/dashboard/directeur/publications': typeof DashboardDirecteurPublicationsRoute
  '/dashboard/doctorant/bilan': typeof DashboardDoctorantBilanRoute
  '/dashboard/doctorant/publications': typeof DashboardDoctorantPublicationsRoute
  '/dashboard/doctorant/these': typeof DashboardDoctorantTheseRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/chercheur': typeof DashboardChercheurIndexRoute
  '/dashboard/directeur': typeof DashboardDirecteurIndexRoute
  '/dashboard/doctorant': typeof DashboardDoctorantIndexRoute
  '/dashboard/directeur/bilans/$id': typeof DashboardDirecteurBilansIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/chercheur': typeof DashboardChercheurRouteWithChildren
  '/dashboard/directeur': typeof DashboardDirecteurRouteWithChildren
  '/dashboard/doctorant': typeof DashboardDoctorantRouteWithChildren
  '/dashboard/admin/directeurs': typeof DashboardAdminDirecteursRoute
  '/dashboard/admin/doctorants': typeof DashboardAdminDoctorantsRoute
  '/dashboard/admin/equipes': typeof DashboardAdminEquipesRoute
  '/dashboard/admin/messages': typeof DashboardAdminMessagesRoute
  '/dashboard/admin/publications': typeof DashboardAdminPublicationsRoute
  '/dashboard/chercheur/bilan': typeof DashboardChercheurBilanRoute
  '/dashboard/chercheur/publications': typeof DashboardChercheurPublicationsRoute
  '/dashboard/directeur/bilans': typeof DashboardDirecteurBilansRouteWithChildren
  '/dashboard/directeur/chercheurs': typeof DashboardDirecteurChercheursRoute
  '/dashboard/directeur/equipes': typeof DashboardDirecteurEquipesRoute
  '/dashboard/directeur/inscriptions': typeof DashboardDirecteurInscriptionsRoute
  '/dashboard/directeur/projets': typeof DashboardDirecteurProjetsRoute
  '/dashboard/directeur/publications': typeof DashboardDirecteurPublicationsRoute
  '/dashboard/doctorant/bilan': typeof DashboardDoctorantBilanRoute
  '/dashboard/doctorant/publications': typeof DashboardDoctorantPublicationsRoute
  '/dashboard/doctorant/these': typeof DashboardDoctorantTheseRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/chercheur/': typeof DashboardChercheurIndexRoute
  '/dashboard/directeur/': typeof DashboardDirecteurIndexRoute
  '/dashboard/doctorant/': typeof DashboardDoctorantIndexRoute
  '/dashboard/directeur/bilans/$id': typeof DashboardDirecteurBilansIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/dashboard/admin'
    | '/dashboard/chercheur'
    | '/dashboard/directeur'
    | '/dashboard/doctorant'
    | '/dashboard/admin/directeurs'
    | '/dashboard/admin/doctorants'
    | '/dashboard/admin/equipes'
    | '/dashboard/admin/messages'
    | '/dashboard/admin/publications'
    | '/dashboard/chercheur/bilan'
    | '/dashboard/chercheur/publications'
    | '/dashboard/directeur/bilans'
    | '/dashboard/directeur/chercheurs'
    | '/dashboard/directeur/equipes'
    | '/dashboard/directeur/inscriptions'
    | '/dashboard/directeur/projets'
    | '/dashboard/directeur/publications'
    | '/dashboard/doctorant/bilan'
    | '/dashboard/doctorant/publications'
    | '/dashboard/doctorant/these'
    | '/dashboard/admin/'
    | '/dashboard/chercheur/'
    | '/dashboard/directeur/'
    | '/dashboard/doctorant/'
    | '/dashboard/directeur/bilans/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/dashboard/admin/directeurs'
    | '/dashboard/admin/doctorants'
    | '/dashboard/admin/equipes'
    | '/dashboard/admin/messages'
    | '/dashboard/admin/publications'
    | '/dashboard/chercheur/bilan'
    | '/dashboard/chercheur/publications'
    | '/dashboard/directeur/bilans'
    | '/dashboard/directeur/chercheurs'
    | '/dashboard/directeur/equipes'
    | '/dashboard/directeur/inscriptions'
    | '/dashboard/directeur/projets'
    | '/dashboard/directeur/publications'
    | '/dashboard/doctorant/bilan'
    | '/dashboard/doctorant/publications'
    | '/dashboard/doctorant/these'
    | '/dashboard/admin'
    | '/dashboard/chercheur'
    | '/dashboard/directeur'
    | '/dashboard/doctorant'
    | '/dashboard/directeur/bilans/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/dashboard/admin'
    | '/dashboard/chercheur'
    | '/dashboard/directeur'
    | '/dashboard/doctorant'
    | '/dashboard/admin/directeurs'
    | '/dashboard/admin/doctorants'
    | '/dashboard/admin/equipes'
    | '/dashboard/admin/messages'
    | '/dashboard/admin/publications'
    | '/dashboard/chercheur/bilan'
    | '/dashboard/chercheur/publications'
    | '/dashboard/directeur/bilans'
    | '/dashboard/directeur/chercheurs'
    | '/dashboard/directeur/equipes'
    | '/dashboard/directeur/inscriptions'
    | '/dashboard/directeur/projets'
    | '/dashboard/directeur/publications'
    | '/dashboard/doctorant/bilan'
    | '/dashboard/doctorant/publications'
    | '/dashboard/doctorant/these'
    | '/dashboard/admin/'
    | '/dashboard/chercheur/'
    | '/dashboard/directeur/'
    | '/dashboard/doctorant/'
    | '/dashboard/directeur/bilans/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardChercheurRoute: typeof DashboardChercheurRouteWithChildren
  DashboardDirecteurRoute: typeof DashboardDirecteurRouteWithChildren
  DashboardDoctorantRoute: typeof DashboardDoctorantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/doctorant': {
      id: '/dashboard/doctorant'
      path: '/dashboard/doctorant'
      fullPath: '/dashboard/doctorant'
      preLoaderRoute: typeof DashboardDoctorantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/directeur': {
      id: '/dashboard/directeur'
      path: '/dashboard/directeur'
      fullPath: '/dashboard/directeur'
      preLoaderRoute: typeof DashboardDirecteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/chercheur': {
      id: '/dashboard/chercheur'
      path: '/dashboard/chercheur'
      fullPath: '/dashboard/chercheur'
      preLoaderRoute: typeof DashboardChercheurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/doctorant/': {
      id: '/dashboard/doctorant/'
      path: '/'
      fullPath: '/dashboard/doctorant/'
      preLoaderRoute: typeof DashboardDoctorantIndexRouteImport
      parentRoute: typeof DashboardDoctorantRoute
    }
    '/dashboard/directeur/': {
      id: '/dashboard/directeur/'
      path: '/'
      fullPath: '/dashboard/directeur/'
      preLoaderRoute: typeof DashboardDirecteurIndexRouteImport
      parentRoute: typeof DashboardDirecteurRoute
    }
    '/dashboard/chercheur/': {
      id: '/dashboard/chercheur/'
      path: '/'
      fullPath: '/dashboard/chercheur/'
      preLoaderRoute: typeof DashboardChercheurIndexRouteImport
      parentRoute: typeof DashboardChercheurRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/doctorant/these': {
      id: '/dashboard/doctorant/these'
      path: '/these'
      fullPath: '/dashboard/doctorant/these'
      preLoaderRoute: typeof DashboardDoctorantTheseRouteImport
      parentRoute: typeof DashboardDoctorantRoute
    }
    '/dashboard/doctorant/publications': {
      id: '/dashboard/doctorant/publications'
      path: '/publications'
      fullPath: '/dashboard/doctorant/publications'
      preLoaderRoute: typeof DashboardDoctorantPublicationsRouteImport
      parentRoute: typeof DashboardDoctorantRoute
    }
    '/dashboard/doctorant/bilan': {
      id: '/dashboard/doctorant/bilan'
      path: '/bilan'
      fullPath: '/dashboard/doctorant/bilan'
      preLoaderRoute: typeof DashboardDoctorantBilanRouteImport
      parentRoute: typeof DashboardDoctorantRoute
    }
    '/dashboard/directeur/publications': {
      id: '/dashboard/directeur/publications'
      path: '/publications'
      fullPath: '/dashboard/directeur/publications'
      preLoaderRoute: typeof DashboardDirecteurPublicationsRouteImport
      parentRoute: typeof DashboardDirecteurRoute
    }
    '/dashboard/directeur/projets': {
      id: '/dashboard/directeur/projets'
      path: '/projets'
      fullPath: '/dashboard/directeur/projets'
      preLoaderRoute: typeof DashboardDirecteurProjetsRouteImport
      parentRoute: typeof DashboardDirecteurRoute
    }
    '/dashboard/directeur/inscriptions': {
      id: '/dashboard/directeur/inscriptions'
      path: '/inscriptions'
      fullPath: '/dashboard/directeur/inscriptions'
      preLoaderRoute: typeof DashboardDirecteurInscriptionsRouteImport
      parentRoute: typeof DashboardDirecteurRoute
    }
    '/dashboard/directeur/equipes': {
      id: '/dashboard/directeur/equipes'
      path: '/equipes'
      fullPath: '/dashboard/directeur/equipes'
      preLoaderRoute: typeof DashboardDirecteurEquipesRouteImport
      parentRoute: typeof DashboardDirecteurRoute
    }
    '/dashboard/directeur/chercheurs': {
      id: '/dashboard/directeur/chercheurs'
      path: '/chercheurs'
      fullPath: '/dashboard/directeur/chercheurs'
      preLoaderRoute: typeof DashboardDirecteurChercheursRouteImport
      parentRoute: typeof DashboardDirecteurRoute
    }
    '/dashboard/directeur/bilans': {
      id: '/dashboard/directeur/bilans'
      path: '/bilans'
      fullPath: '/dashboard/directeur/bilans'
      preLoaderRoute: typeof DashboardDirecteurBilansRouteImport
      parentRoute: typeof DashboardDirecteurRoute
    }
    '/dashboard/chercheur/publications': {
      id: '/dashboard/chercheur/publications'
      path: '/publications'
      fullPath: '/dashboard/chercheur/publications'
      preLoaderRoute: typeof DashboardChercheurPublicationsRouteImport
      parentRoute: typeof DashboardChercheurRoute
    }
    '/dashboard/chercheur/bilan': {
      id: '/dashboard/chercheur/bilan'
      path: '/bilan'
      fullPath: '/dashboard/chercheur/bilan'
      preLoaderRoute: typeof DashboardChercheurBilanRouteImport
      parentRoute: typeof DashboardChercheurRoute
    }
    '/dashboard/admin/publications': {
      id: '/dashboard/admin/publications'
      path: '/publications'
      fullPath: '/dashboard/admin/publications'
      preLoaderRoute: typeof DashboardAdminPublicationsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/messages': {
      id: '/dashboard/admin/messages'
      path: '/messages'
      fullPath: '/dashboard/admin/messages'
      preLoaderRoute: typeof DashboardAdminMessagesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/equipes': {
      id: '/dashboard/admin/equipes'
      path: '/equipes'
      fullPath: '/dashboard/admin/equipes'
      preLoaderRoute: typeof DashboardAdminEquipesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/doctorants': {
      id: '/dashboard/admin/doctorants'
      path: '/doctorants'
      fullPath: '/dashboard/admin/doctorants'
      preLoaderRoute: typeof DashboardAdminDoctorantsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/directeurs': {
      id: '/dashboard/admin/directeurs'
      path: '/directeurs'
      fullPath: '/dashboard/admin/directeurs'
      preLoaderRoute: typeof DashboardAdminDirecteursRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/directeur/bilans/$id': {
      id: '/dashboard/directeur/bilans/$id'
      path: '/$id'
      fullPath: '/dashboard/directeur/bilans/$id'
      preLoaderRoute: typeof DashboardDirecteurBilansIdRouteImport
      parentRoute: typeof DashboardDirecteurBilansRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminDirecteursRoute: typeof DashboardAdminDirecteursRoute
  DashboardAdminDoctorantsRoute: typeof DashboardAdminDoctorantsRoute
  DashboardAdminEquipesRoute: typeof DashboardAdminEquipesRoute
  DashboardAdminMessagesRoute: typeof DashboardAdminMessagesRoute
  DashboardAdminPublicationsRoute: typeof DashboardAdminPublicationsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminDirecteursRoute: DashboardAdminDirecteursRoute,
  DashboardAdminDoctorantsRoute: DashboardAdminDoctorantsRoute,
  DashboardAdminEquipesRoute: DashboardAdminEquipesRoute,
  DashboardAdminMessagesRoute: DashboardAdminMessagesRoute,
  DashboardAdminPublicationsRoute: DashboardAdminPublicationsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardChercheurRouteChildren {
  DashboardChercheurBilanRoute: typeof DashboardChercheurBilanRoute
  DashboardChercheurPublicationsRoute: typeof DashboardChercheurPublicationsRoute
  DashboardChercheurIndexRoute: typeof DashboardChercheurIndexRoute
}

const DashboardChercheurRouteChildren: DashboardChercheurRouteChildren = {
  DashboardChercheurBilanRoute: DashboardChercheurBilanRoute,
  DashboardChercheurPublicationsRoute: DashboardChercheurPublicationsRoute,
  DashboardChercheurIndexRoute: DashboardChercheurIndexRoute,
}

const DashboardChercheurRouteWithChildren =
  DashboardChercheurRoute._addFileChildren(DashboardChercheurRouteChildren)

interface DashboardDirecteurBilansRouteChildren {
  DashboardDirecteurBilansIdRoute: typeof DashboardDirecteurBilansIdRoute
}

const DashboardDirecteurBilansRouteChildren: DashboardDirecteurBilansRouteChildren =
  {
    DashboardDirecteurBilansIdRoute: DashboardDirecteurBilansIdRoute,
  }

const DashboardDirecteurBilansRouteWithChildren =
  DashboardDirecteurBilansRoute._addFileChildren(
    DashboardDirecteurBilansRouteChildren,
  )

interface DashboardDirecteurRouteChildren {
  DashboardDirecteurBilansRoute: typeof DashboardDirecteurBilansRouteWithChildren
  DashboardDirecteurChercheursRoute: typeof DashboardDirecteurChercheursRoute
  DashboardDirecteurEquipesRoute: typeof DashboardDirecteurEquipesRoute
  DashboardDirecteurInscriptionsRoute: typeof DashboardDirecteurInscriptionsRoute
  DashboardDirecteurProjetsRoute: typeof DashboardDirecteurProjetsRoute
  DashboardDirecteurPublicationsRoute: typeof DashboardDirecteurPublicationsRoute
  DashboardDirecteurIndexRoute: typeof DashboardDirecteurIndexRoute
}

const DashboardDirecteurRouteChildren: DashboardDirecteurRouteChildren = {
  DashboardDirecteurBilansRoute: DashboardDirecteurBilansRouteWithChildren,
  DashboardDirecteurChercheursRoute: DashboardDirecteurChercheursRoute,
  DashboardDirecteurEquipesRoute: DashboardDirecteurEquipesRoute,
  DashboardDirecteurInscriptionsRoute: DashboardDirecteurInscriptionsRoute,
  DashboardDirecteurProjetsRoute: DashboardDirecteurProjetsRoute,
  DashboardDirecteurPublicationsRoute: DashboardDirecteurPublicationsRoute,
  DashboardDirecteurIndexRoute: DashboardDirecteurIndexRoute,
}

const DashboardDirecteurRouteWithChildren =
  DashboardDirecteurRoute._addFileChildren(DashboardDirecteurRouteChildren)

interface DashboardDoctorantRouteChildren {
  DashboardDoctorantBilanRoute: typeof DashboardDoctorantBilanRoute
  DashboardDoctorantPublicationsRoute: typeof DashboardDoctorantPublicationsRoute
  DashboardDoctorantTheseRoute: typeof DashboardDoctorantTheseRoute
  DashboardDoctorantIndexRoute: typeof DashboardDoctorantIndexRoute
}

const DashboardDoctorantRouteChildren: DashboardDoctorantRouteChildren = {
  DashboardDoctorantBilanRoute: DashboardDoctorantBilanRoute,
  DashboardDoctorantPublicationsRoute: DashboardDoctorantPublicationsRoute,
  DashboardDoctorantTheseRoute: DashboardDoctorantTheseRoute,
  DashboardDoctorantIndexRoute: DashboardDoctorantIndexRoute,
}

const DashboardDoctorantRouteWithChildren =
  DashboardDoctorantRoute._addFileChildren(DashboardDoctorantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardChercheurRoute: DashboardChercheurRouteWithChildren,
  DashboardDirecteurRoute: DashboardDirecteurRouteWithChildren,
  DashboardDoctorantRoute: DashboardDoctorantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
